name: 'Readme Generator'
on:
  push:
    branches:
     - master
  schedule:
     - cron: "0 */1 * * *"

jobs:
  readme:
    name: "Readme generator"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update README
          branch: master
          commit_user_name: zaifastafa
          commit_user_email: hello@huzaifamustafa.com
          commit_author: Huzaifa Mustafa <hello@huzaifamustafa.com>
